### ISSUE TITLE
Batch Subscribing

### ISSUE THREAD

**Issue by onato** [centrifugal/centrifuge-swift#52]
On one of my screens, I subscribe to a large number of channels. Currently, this means an HTTPS request for each subscription. 

I noticed that the JS library supports batch subscriptions. Are there any plans to implement this here too?

**Comment by FZambia** [comment]
Hello, I think you can do batching yourself by implementing it on top of existing onPrivateSub callback. I.e. have a way to merge individual callbacks together and issue a single HTTP request for tokens (using explicit signal or by time/size).

Maybe this entity will be generic enough and so that we could include it in centrifuge-swift core eventually, like a separate helper.

**Comment by onato** [comment]
Quite right, I'll do it in my code for now and submit a pull request if I generalize it enough to be useful to others.
