### ISSUE TITLE
Why it doesn't work with protocol=json

### ISSUE THREAD

**Issue by Alexborodalex** [centrifugal/centrifuge-swift#76]

**Comment by FZambia** [comment]
Hello, @Alexborodalex 

JSON protocol format is not implemented by centrifuge-swift. It only works over Protobuf. See https://centrifugal.dev/docs/transports/client_sdk#protobuf-and-json-formats-in-sdks. Though you can still use JSON payloads here, since JSON is just a sequence of bytes and may be transmitted over Protobuf - [example](https://github.com/centrifugal/centrifuge-swift/blob/master/Example/SwiftCentrifuge/ViewController.swift#L64).

Is your question caused by some problem you came across?
